# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42b559ba-d3a0-4d88-89df-666a70a36404";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/99152419-218c-457a-8dc9-47983844f52d";

  swapDevices = [ 
    { device = "/swapfile";
      priority = 100;
      size = 8192;
    }
  ];

  nix.maxJobs = lib.mkDefault 16;
}
